<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: mysql
  database: quippo_development
  username: root
  password: 
  host: localhost
  encoding: utf8

test: &TEST
  adapter: mysql
  database: quippo_test
  username: root
  password: 
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: quippo_production
  username: quippo
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *TEST