development:
  adapter: postgresql
  database: quippo_development
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: quippo_test
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: quippo_production
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000