#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

options = {
    :app_name   => 'tracker',
    :dir_mode   => :script,
    :dir        => '../tmp/pids',
    :backtrace  => true
  }

Daemons.run(File.join(File.dirname(__FILE__), 'tracker.rb'), options)